new(userspace/libsinsp): introduce sinsp_dns_manager.clear_cache method, improve performance, fix concurrency issue
falcosecurity/libs pull request #120
Opened 2021-11-04 00:47 UTC by VadimZy

**What type of PR is this?**

> /kind bug

> /kind feature

**Any specific area of the project related to this PR?**

> /area libsinsp

**What this PR does / why we need it**:
when reloading Falco policies we need to clear DNS lookup cache, otherwise, the refresher will refresh-lookup names for disabled rules up to 1 hour - the cache TTL.
In particular: 
> Customer is looking to stop receiving AWS GuardDuty alarms after disabling the Cryptomining rule in the Secure UI which executes DNS lookups

**Which issue(s) this PR fixes**:

In the current implementation, there is a thread-unsafe assignment:
```
if(refreshed_info != info)
{
        info = refreshed_info;
}
```

**Does this PR introduce a user-facing change?**:
new method:
```
sinsp_dns_manager::clear_cache() 
```

2021-11-04 00:47 UTC, poiana commented
@VadimZy: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-04 00:47 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/libs/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [9dd7e63](https://github.com/falcosecurity/libs/commits/9dd7e6399ed02ca6d827c9b34a20772e5ccd412d) SSPROD-9650 Update DNS lookup cache in libsinp to introduce a way to clean up the policy disabled/deleted entries
- [2506a32](https://github.com/falcosecurity/libs/commits/2506a328f25a52a3e159bc3934ef03389f4aca7f) fix test errors
- [5945d75](https://github.com/falcosecurity/libs/commits/5945d758e5bde87f19c882931b07c213fb7f2d10) use tbb hashes instead of local dns_info sets
- [3ffce7f](https://github.com/falcosecurity/libs/commits/3ffce7ff4819ac1f4f9a77802dbfa8b5378689be) Implement DNS cache cleanup, fix concurrency problems.
- [d84443b](https://github.com/falcosecurity/libs/commits/d84443bb489341dd9541587def2ed93c7ac40bbd) refresh thread creation moved
- [00802db](https://github.com/falcosecurity/libs/commits/00802db95970ffb84d07d36fe01fd4d3deb48a7b) code comments
- [1aebc0e](https://github.com/falcosecurity/libs/commits/1aebc0e8f517d2c69d6bc58ca08992469c2343f4) add const qualifiers
- [7672884](https://github.com/falcosecurity/libs/commits/76728841622c6037d864d6b0e783bc6e5c7aa4ff) on-prem tests/validation
- [d5cda29](https://github.com/falcosecurity/libs/commits/d5cda29502277d4430bee749c83934f4fd22646e) on-prem tests/validation

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-11-04 00:47 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/libs/pull/120#" title="Author self-approved">VadimZy</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ldegio** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @ldegio` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Flibs).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/libs/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["ldegio"]} -->

2021-11-04 00:47 UTC, poiana commented
Hi @VadimZy. Thanks for your PR.

I'm waiting for a [falcosecurity](https://github.com/orgs/falcosecurity/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Flibs).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-05 10:12 UTC, FedeDP commented
Hi! Thanks for opening this PR!
Can you squash your commits and sign the commit with dco? 
Thank you very much!

2021-11-12 09:16 UTC, leogr requested changes
Hey @VadimZy 

Thank you for opening this PR. Anyway, before looking to your PR, we need all commits to be [signed off](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).

Moreover, I have noticed that you used a reference (SSPROD-9650) in a commit message to something extraneous to this organization. I believe that reference may be misleading for those who look at the code. Could you remove that, please?

2022-01-02 21:27 UTC, VadimZy commented
@leogr 
Closing this one to open:
https://github.com/falcosecurity/libs/pull/166
all commits are squeezed into a single one.

2022-01-02 21:27 UTC, closed without merging