update: extend PT_CHARBUFARRAY param type and support it in plugins
falcosecurity/libs pull request #200
Opened 2022-02-09 10:16 UTC by jasondellaluce

**What type of PR is this?**

/kind bug

/kind feature

**Any specific area of the project related to this PR?**

/area libscap

/area libsinsp

**What this PR does / why we need it**:

The event parameter type `PT_CHARBUFARRAY` was defined but only used internally. Now, code it has been changed to be fully supported like the other parameter types.

`PT_CHARBUFARRAY` represents a list of one or more strings. Although not fully documented, this was already supported by Falco with the k8s audit log filter checks. Now, this needs to be supported natively in libsinsp in order to allow plugins to use list filtercheck types too. Morover, libsinp is also the right place as it bundles the logic for all the other
event parameter types.

Filterchecks of type `PT_CHARBUFARRAY` only support list-based operators: `in`, `intersects`, and `pmatch`. Using it with other operators leads to an error.

If formatted as a string, the output is a list such as `"(item1,item2,...,itemN)"`. This is not safe for
string escaping, and creates an ambiguity on the `,` separator character. However, this is how Falco implemented
this already, and I reported it faithfully for backward compatibility. If formatted as a json, the output is a json-formatted list.

The plugin API has been updated to support a new `string[]` extraction field type.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update: extend PT_CHARBUFARRAY param type and support it in plugins
```

2022-02-09 10:16 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/libs/pull/200#" title="Author self-approved">jasondellaluce</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **fededp** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @fededp` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Flibs).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/libs/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fededp"]} -->

2022-02-09 10:19 UTC, jasondellaluce commented on userspace/chisel/chisel_api.cpp
> +		case PT_CHARBUFARRAY:
I'm not 100% confident that this is what we want here, but I think flattening the list to a string would work for chisels.

2022-02-09 10:43 UTC, poiana commented
@jasondellaluce: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-with-chisels | 9a14e673e70bdc9a2d56347e1bdd1dccc26a1246 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/200/build-libs-with-chisels/1491355213045436416) | true | `/test build-libs-with-chisels`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=200). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-09 11:57 UTC, jasondellaluce commented
NOTE: We can also consider an alternative approach, such as changing the signature of the `extract` method of filterchecks to populate a vector of results. I personally would like this other approach more from a design perspective, but it would require quite a huge refactoring in many parts of libsinsp (and a breaking change in the plugin API), which could end up breaking lots of code parts. Let's have a discussion about this.

2022-02-09 13:56 UTC, FedeDP commented
I think the latter one could be the best implementation; while the refactor will be huge, we can work on it together.  
The most problematic thing is that the diff would be huge, and it cannot be broken into small commits. But i guess that's fairly ok, given the refactoring.
+1 on the alternative approach from me!

2022-02-09 22:49 UTC, mstemm requested changes
Thanks for being so diligent. I tried to see if you caught all the places where we needed to add support and I think you already found them all!

Just a few minor comments.

2022-02-09 22:49 UTC, mstemm commented on userspace/libsinsp/filter.cpp
> +			strncpy(m_getpropertystr_storage,
I think you could make this simpler by adding a generic m_getproperty_strval or similar to sinsp_filter_check, building a string containing the values as you're doing, and then returning a `.c_str()` cast to non-const.

A lot of other filterchecks do a similar thing like sinsp_filter_check_user and m_strval, sinsp_filter_check_tracer and m_strstorage, etc.

2022-02-09 22:49 UTC, mstemm commented on userspace/libsinsp/filter.cpp
> +			else if (op == CO_PMATCH)
I know that pmatch was supported for json events (falco json_evt.cpp), but I don't see it used in the k8s audit rules, and it's kind of complicated to explain-- "(/some/path, /other/path) pmatch (/bin, /usr) returns true if *any* value on the left hand side has any of the values on the right hand side as a prefix". Do you think this is too complex to bother supporting?

2022-02-09 22:49 UTC, mstemm commented on userspace/libsinsp/filter.cpp
> +	else if(compare_no_consume("in"))
Yeah, I always wished we could use a real parser for this, leading comments in filter.cpp notwithstanding.

2022-02-09 22:49 UTC, mstemm commented on userspace/libsinsp/filter.cpp
> +		case PT_CHARBUFARRAY:
Can you also update the comment block on lines ~1223-~1226, now that filterchecks *can* extract multiple values?

2022-02-09 22:49 UTC, mstemm commented on userspace/chisel/chisel_api.cpp
> +		case PT_CHARBUFARRAY:
Totally fine with just skipping these for now, but maybe a comment saying that a complete solution would involve creating a lua table, populating it with the values, and pushing that onto the stack?

2022-02-09 22:49 UTC, mstemm commented on userspace/libsinsp/filter.cpp
> +		throw sinsp_exception("charbuf-array type can't be compared to single values");
How about a comment stating that the caller ensures that flt_compare is never called with a PT_CHARBUFARRAY? I originally thought that a badly written filter might result in this exception and thought it was too aggressive.

2022-02-11 15:06 UTC, jasondellaluce commented
This is closed in favor of #201, which solves the same problem with a better approach.

2022-02-11 15:06 UTC, closed without merging