new(driver): update exit events `PPME_SYSCALL_WRITE_X` and `PPME_SYSCALL_PWRITE_X` with enter params
falcosecurity/libs pull request #2187
Opened 2024-12-05 10:44 UTC by Andreagit97

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area driver-kmod

/area driver-bpf

/area driver-modern-bpf

/area libscap-engine-gvisor

/area libscap

/area libsinsp

/area tests

**Does this PR require a change in the driver versions?**

/version driver-SCHEMA-version-major

**What this PR does / why we need it**:

This PR is part of https://github.com/falcosecurity/libs/pull/2068. 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2024-12-05 10:44 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/libs/pull/2187#" title="Author self-approved">Andreagit97</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Flibs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/libs/blob/master/OWNERS)~~ [Andreagit97]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2024-12-16 11:44 UTC, Andreagit97 commented
This needs https://github.com/falcosecurity/libs/pull/2202

2024-12-17 10:35 UTC, FedeDP submitted a review, later dismissed
/approve

2024-12-17 10:35 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: d2563eeb0a9f2401dac00ba2c0041ef632b8aa55</details>

2025-01-07 13:46 UTC, leogr commented
/milestone 0.21.0

2025-01-16 08:54 UTC, ekoops requested changes
Overall lgtm. Would you mind to rebase and bump just the minor in `SCHEMA_VERSION` and `SCAP_MINIMUM_DRIVER_SCHEMA_VERSION` instead of bumping the major?

2025-01-16 08:54 UTC, poiana commented
@ekoops: changing LGTM is restricted to collaborators

<details>

In response to [this](https://github.com/falcosecurity/libs/pull/2187#pullrequestreview-2555254406):

>Overall lgtm. Would you mind to rebase and bump just the minor in `SCHEMA_VERSION` and `SCAP_MINIMUM_DRIVER_SCHEMA_VERSION` instead of bumping the major?


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository.
</details>

2025-01-17 11:40 UTC, poiana commented
New changes are detected. LGTM label has been removed.

2025-01-17 11:41 UTC, Andreagit97 commented
Rebased on top of master

2025-01-17 14:27 UTC, leogr approved these changes
:+1: 

/hold 0.21.0

2025-01-17 14:27 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: fec5c8b45e6a3f06ff3852a3476f9cbdcb3e2da9</details>

2025-01-20 13:37 UTC, FedeDP approved these changes
/approve

2025-01-20 13:37 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/libs/pull/2187#" title="Author self-approved">Andreagit97</a>*, *<a href="https://github.com/falcosecurity/libs/pull/2187#pullrequestreview-2562416505" title="Approved">FedeDP</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Flibs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/libs/blob/master/OWNERS)~~ [Andreagit97,FedeDP]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2025-01-20 19:08 UTC, merged