docs: add libsinsp example code and documentation
falcosecurity/libs pull request #34
Opened 2021-04-14 17:21 UTC by dwindsor-scwx

Signed-off-by: David Windsor <dwindsor@secureworks.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:
 /kind documentation

> Uncomment one (or more) `/area <>` lines:
/area libsinsp

**What this PR does / why we need it**:
add libsinsp example code and documentation

**Which issue(s) this PR fixes**: 
https://github.com/falcosecurity/libs/issues/31

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2021-04-14 17:21 UTC, poiana commented
@dwindsor-scwx: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-04-14 17:21 UTC, poiana commented
Welcome @dwindsor-scwx! It looks like this is your first PR to falcosecurity/libs 🎉

2021-04-14 17:21 UTC, poiana commented
Hi @dwindsor-scwx. Thanks for your PR.

I'm waiting for a [falcosecurity](https://github.com/orgs/falcosecurity/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/falcosecurity/.github/blob/master/GOVERNANCE.md) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Flibs).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-04-14 17:21 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **leogr** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @leogr` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Flibs).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/libs/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2021-04-20 07:25 UTC, leogr commented
/ok-to-test

2021-04-20 07:45 UTC, poiana commented
@dwindsor-scwx: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-libs-bundled-deps | f26f089880b4232c47a1fafe263dd45887df4852 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/34/build-libs-bundled-deps/1384407888402845696) | `/test build-libs-bundled-deps`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=34). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-20 07:45 UTC, poiana commented
@dwindsor-scwx: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-libs-bundled-deps | f26f089880b4232c47a1fafe263dd45887df4852 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/34/build-libs-bundled-deps/1384407888402845696) | `/test build-libs-bundled-deps`
build-libs | f26f089880b4232c47a1fafe263dd45887df4852 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/34/build-libs/1384407888310571008) | `/test build-libs`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=34). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-20 08:12 UTC, leogr reviewed
This is a great contribution! Thank you :100: 

Just one question: could we avoid depending on "chisel"? It would great if the example would not rely on that since we are trying to make "chisel" completely optional and not enabled by default.

2021-04-20 12:59 UTC, dwindsor-scwx commented
> This is a great contribution! Thank you 💯
> 
> Just one question: could we avoid depending on "chisel"? It would great if the example would not rely on that since we are trying to make "chisel" completely optional and not enabled by default.

Sure! Does it make sense to perhaps split this one example into two example programs: one that demonstrates the usage of chisels/filters and one that doesn't? I'm not actually too clear on the separation between filters and chisels.

2021-04-21 08:51 UTC, leogr commented
> > This is a great contribution! Thank you 100
> > Just one question: could we avoid depending on "chisel"? It would great if the example would not rely on that since we are trying to make "chisel" completely optional and not enabled by default.
> 
> Sure! Does it make sense to perhaps split this one example into two example programs: one that demonstrates the usage of chisels/filters and one that doesn't? I'm not actually too clear on the separation between filters and chisels.

A [chisel](https://github.com/draios/sysdig/wiki/Writing-a-Sysdig-Chisel,-a-Tutorial) is a Lua program that works on top filters and data collected by the libs. AFAIK, chisels are used only by `sysdig` CLI. Btw, they are completely optional. I recently moved them to the `userspace/chisel` folder for this reason, so consumers can avoid depending on them (and their dependencies) when they are not needed. Maybe, one day they could become a separate library.

I see in your example, `chisel.h` is imported only for this :point_down: :
https://github.com/falcosecurity/libs/pull/34/files#diff-7a7e437b41e679bace70e956e04d3e2a2a70b54c51baf7209b2cdfe0295efaf5R97

That seems to me not really needed (I have not tested the code, but I guess so). Moreover, chisels are not related to Falco rules files and that line won't load rules from the given directory. 

So, my advice is just to do not include chisels in this example. We could later, in another PR, show chisel in another example eventually, even though I have no clear idea how to do that atm.

Let me know if you need further info and feel free to DM me over slack if you need any help! :+1:

2021-04-27 07:48 UTC, leogr commented
/retest

2021-04-29 14:02 UTC, leogr requested changes
I've added some suggestions to set the correct license headers.
See below.

2021-04-29 14:02 UTC, leogr commented on userspace/libsinsp/examples/test.cpp
> +This file is part of sysdig.
```suggestion
Copyright (C) 2021 The Falco Authors.
```

2021-04-29 14:02 UTC, leogr commented on userspace/libsinsp/examples/util.cpp
> +This file is part of sysdig.
```suggestion
Copyright (C) 2021 The Falco Authors.
```

2021-04-29 14:02 UTC, leogr commented on userspace/libsinsp/examples/util.h
> +This file is part of sysdig.
```suggestion
Copyright (C) 2021 The Falco Authors.
```

2021-04-29 14:41 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/libs/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [b0f238f](https://github.com/falcosecurity/libs/commits/b0f238f773cd69ecb1a93fb3426c622a43334cf0) Fix license headers

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-04-29 14:41 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **leogr** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Flibs).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/libs/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2021-04-29 14:45 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/libs/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [b0f238f](https://github.com/falcosecurity/libs/commits/b0f238f773cd69ecb1a93fb3426c622a43334cf0) Fix license headers
- [af6c79e](https://github.com/falcosecurity/libs/commits/af6c79e4234ee608fc99e6557d82bffe190b92f1) Merge branch 'docs/libsinsp-docs' of github.com:dwindsor-scwx/libs into docs/libsinsp-docs

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-04-29 14:45 UTC, poiana commented
@dwindsor-scwx: Adding label `do-not-merge/contains-merge-commits` because PR contains merge commits, which are not allowed in this repository.
Use `git rebase` to reapply your commits on top of the target branch. Detailed instructions for doing so can be found [here](https://git.k8s.io/community/contributors/guide/github-workflow.md#4-keep-your-branch-in-sync).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-04-29 14:49 UTC, dwindsor commented on userspace/libsinsp/examples/test.cpp
> +This file is part of sysdig.
Fixed

2021-04-29 14:49 UTC, dwindsor commented on userspace/libsinsp/examples/util.cpp
> +This file is part of sysdig.
Fixed

2021-04-29 14:49 UTC, dwindsor commented on userspace/libsinsp/examples/util.h
> +This file is part of sysdig.
Fixed

2021-05-05 09:38 UTC, leogr approved these changes

2021-05-05 09:51 UTC, leodido reviewed
Thanks for submitting this @dwindsor-scwx

I only left a suggestion (mind accepting it?) to link to falcosecurity docs

2021-05-05 09:51 UTC, leodido commented on userspace/libsinsp/examples/README.md
> +To use filtering, specify a [Sysdig filter](https://github.com/draios/sysdig/wiki/Sysdig-User-Guide#all-supported-filters) using `-f`.
```suggestion
To use filtering, specify a [filter](https://falco.org/docs/rules/supported-fields/#system-calls-source-syscall) using `-f`.
```

2021-05-05 11:18 UTC, dwindsor submitted a review, later dismissed

2021-05-05 11:19 UTC, poiana commented
@dwindsor: changing LGTM is restricted to collaborators

<details>

In response to [this](https://github.com/falcosecurity/libs/pull/34#pullrequestreview-652187238):

>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-05-05 11:27 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/libs/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [4f490d3](https://github.com/falcosecurity/libs/commits/4f490d3a3f1628afeef4b374a69e8bbe25dcd031) Update userspace/libsinsp/examples/README.md

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-05-05 11:27 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/libs/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [4f490d3](https://github.com/falcosecurity/libs/commits/4f490d3a3f1628afeef4b374a69e8bbe25dcd031) Update userspace/libsinsp/examples/README.md

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-05-05 11:30 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/libs/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [4f490d3](https://github.com/falcosecurity/libs/commits/4f490d3a3f1628afeef4b374a69e8bbe25dcd031) Update userspace/libsinsp/examples/README.md
- [0c8fd64](https://github.com/falcosecurity/libs/commits/0c8fd64e3e240a9a0e3df105416f7effb2043690) Merge branch 'docs/libsinsp-docs' of github.com:dwindsor-scwx/libs into docs/libsinsp-docs

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-05-05 11:30 UTC, poiana commented
@dwindsor-scwx: Adding label `do-not-merge/contains-merge-commits` because PR contains merge commits, which are not allowed in this repository.
Use `git rebase` to reapply your commits on top of the target branch. Detailed instructions for doing so can be found [here](https://git.k8s.io/community/contributors/guide/github-workflow.md#4-keep-your-branch-in-sync).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-05-05 11:38 UTC, dwindsor-scwx commented
> Thanks for submitting this @dwindsor-scwx
> 
> I only left a suggestion (mind accepting it?) to link to falcosecurity docs

I tried accepting it, but from the wrong github account accidentally.

2021-05-05 11:49 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/libs/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [9f99351](https://github.com/falcosecurity/libs/commits/9f9935151a19eb4cc2dd2f2366f978533f3e1266) Apply suggestions from code review

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-05-05 11:50 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/libs/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [9f99351](https://github.com/falcosecurity/libs/commits/9f9935151a19eb4cc2dd2f2366f978533f3e1266) Apply suggestions from code review

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-05-05 12:03 UTC, leodido approved these changes

2021-05-05 12:03 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 08bb1cfecbb61461f6f8ffcac2e3c7496e757203</details>

2021-05-05 13:19 UTC, leodido submitted a review, later dismissed

2021-05-05 15:27 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **leodido** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Flibs).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/libs/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leodido"]} -->

2021-05-05 15:36 UTC, leogr approved these changes
/approve

2021-05-05 15:36 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/libs/pull/34#pullrequestreview-652458506" title="Approved">leogr</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Flibs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/libs/blob/master/OWNERS)~~ [leogr]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-05-05 15:41 UTC, leodido commented
/approve

2021-05-05 15:42 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/libs/pull/34#issuecomment-832795389" title="Approved">leodido</a>*, *<a href="https://github.com/falcosecurity/libs/pull/34#pullrequestreview-652458506" title="Approved">leogr</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Flibs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/libs/blob/master/OWNERS)~~ [leodido,leogr]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-05-05 15:49 UTC, merged