Minor improvements
falcosecurity/libs pull request #86
Opened 2021-09-21 14:10 UTC by FedeDP

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind cleanup

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area libscap

**What this PR does / why we need it**:

It is divided in 2 separate commits:
* first one will make use of c11 `_Static_assert()` for g_syscall_info_table and g_event_info. This means that any issue is caught at compile time. Moreover, with static_assert() we also cover the cases where the expected size was greater than actually declared fields (before we would've empty fields, but the array size was fixed during declaration)
*  Avoid defining enum fields value when they start from 0 and grow by 1; this is a stylish commit to increase code readability with the side effect to mandate less chance of errors (eg: forgetting to increase enum MAX value)

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2021-09-21 14:10 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/libs/pull/86#" title="Author self-approved">FedeDP</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ldegio** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @ldegio` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Flibs).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/libs/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["ldegio"]} -->

2021-09-21 14:10 UTC, poiana commented
Hi @FedeDP. Thanks for your PR.

I'm waiting for a [falcosecurity](https://github.com/orgs/falcosecurity/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Flibs).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-09-21 14:12 UTC, leogr commented
/ok-to-test

2021-09-21 14:18 UTC, poiana commented
@FedeDP: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-libs-with-chisels | 7f8ed3eacbaa69e1d658518f221ce3932b9803cd | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-with-chisels/1440318121159168000) | `/test build-libs-with-chisels`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-21 14:18 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-libs-with-chisels | 7f8ed3eacbaa69e1d658518f221ce3932b9803cd | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-with-chisels/1440318121159168000) | `/test build-libs-with-chisels`
build-libs | 7f8ed3eacbaa69e1d658518f221ce3932b9803cd | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs/1440318120987201536) | `/test build-libs`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-21 14:18 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-libs-with-chisels | 7f8ed3eacbaa69e1d658518f221ce3932b9803cd | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-with-chisels/1440318121159168000) | `/test build-libs-with-chisels`
build-libs | 7f8ed3eacbaa69e1d658518f221ce3932b9803cd | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs/1440318120987201536) | `/test build-libs`
build-libs-bundled-deps | 7f8ed3eacbaa69e1d658518f221ce3932b9803cd | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-bundled-deps/1440318121092059136) | `/test build-libs-bundled-deps`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-12 14:33 UTC, poiana commented
@FedeDP: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-minimal | cbcb25c144af979dc1f6567b696855f97a2de116 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1459166705606463488) | true | `/test build-libs-minimal`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-15 13:10 UTC, FedeDP commented
Rebased on master.

2021-11-15 13:10 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-minimal | cbcb25c144af979dc1f6567b696855f97a2de116 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1459166705606463488) | true | `/test build-libs-minimal`
build-libs | 338fdddf3270c1f5d442bfbd8662731fc3aa0c59 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs/1460233633913638912) | true | `/test build-libs`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-15 13:10 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-minimal | cbcb25c144af979dc1f6567b696855f97a2de116 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1459166705606463488) | true | `/test build-libs-minimal`
build-libs | 338fdddf3270c1f5d442bfbd8662731fc3aa0c59 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs/1460233633913638912) | true | `/test build-libs`
build-libs-bundled-deps | 338fdddf3270c1f5d442bfbd8662731fc3aa0c59 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-bundled-deps/1460233634379206656) | true | `/test build-libs-bundled-deps`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-15 13:10 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-minimal | cbcb25c144af979dc1f6567b696855f97a2de116 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1459166705606463488) | true | `/test build-libs-minimal`
build-libs | 338fdddf3270c1f5d442bfbd8662731fc3aa0c59 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs/1460233633913638912) | true | `/test build-libs`
build-libs-bundled-deps | 338fdddf3270c1f5d442bfbd8662731fc3aa0c59 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-bundled-deps/1460233634379206656) | true | `/test build-libs-bundled-deps`
build-libs-with-chisels | 338fdddf3270c1f5d442bfbd8662731fc3aa0c59 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-with-chisels/1460233634794442752) | true | `/test build-libs-with-chisels`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-15 13:10 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs | 338fdddf3270c1f5d442bfbd8662731fc3aa0c59 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs/1460233633913638912) | true | `/test build-libs`
build-libs-bundled-deps | 338fdddf3270c1f5d442bfbd8662731fc3aa0c59 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-bundled-deps/1460233634379206656) | true | `/test build-libs-bundled-deps`
build-libs-with-chisels | 338fdddf3270c1f5d442bfbd8662731fc3aa0c59 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-with-chisels/1460233634794442752) | true | `/test build-libs-with-chisels`
build-libs-minimal | 338fdddf3270c1f5d442bfbd8662731fc3aa0c59 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1460233635226456064) | true | `/test build-libs-minimal`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-25 13:18 UTC, leogr commented
Closing and reopening to trigger the CI
/close

2021-11-25 13:18 UTC, poiana commented
@leogr: Closed this PR.

<details>

In response to [this](https://github.com/falcosecurity/libs/pull/86#issuecomment-979208282):

>Closing and reopening to trigger the CI
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-25 13:18 UTC, leogr commented
/reopen

2021-11-25 13:19 UTC, poiana commented
@leogr: Reopened this PR.

<details>

In response to [this](https://github.com/falcosecurity/libs/pull/86#issuecomment-979208421):

>/reopen


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-02-01 09:20 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/libs/pull/86#" title="Author self-approved">FedeDP</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Flibs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/libs/blob/master/OWNERS)~~ [FedeDP]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-02-01 09:43 UTC, poiana commented
@FedeDP: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-minimal | 7c8ec91b7c5af70abe9007be44b972176c499be0 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1488446888817463296) | true | `/test build-libs-minimal`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-02 10:54 UTC, poiana commented
@FedeDP: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-minimal | 373ec4ed037fa9c3a7f3b1a83fc12d669254a170 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1488827229671526400) | true | `/test build-libs-minimal`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-07 17:13 UTC, mstemm requested changes
@FedeDP could you include the note from the standard about the last element of a struct and how it doesn't change the size of the struct? That's an important consideration.

We'll just need to make sure that part of the standard is honored by most compilers. (We'll need to think of windows as well, as windows does often read trace files).

2022-02-08 09:01 UTC, FedeDP commented on driver/ppm_events_public.h
> +	uint8_t payload[]; /* Flexible array member for event payload, ie: both len headers + event data */
Included the note!
Flexible array member is part of c99; i think we are still using ansi C89 (or C90)?
Do anyone use compilers that old anymore? I mean, can't we jump to C99?

2022-02-08 09:04 UTC, FedeDP commented on driver/ppm_events_public.h
> +	uint8_t payload[]; /* Flexible array member for event payload, ie: both len headers + event data */
I think C99 is fully supported since gcc 4.3: https://gcc.gnu.org/c99status.html

2022-03-22 08:59 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-arm | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-arm/1506192656869363712) | true | `/test build-libs-arm`
build-libs-minimal | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1506192657020358656) | true | `/test build-libs-minimal`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-22 08:59 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-arm | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-arm/1506192656869363712) | true | `/test build-libs-arm`
build-libs-minimal | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1506192657020358656) | true | `/test build-libs-minimal`
build-libs | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs/1506192656823226368) | true | `/test build-libs`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-22 09:00 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-arm | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-arm/1506192656869363712) | true | `/test build-libs-arm`
build-libs-minimal | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1506192657020358656) | true | `/test build-libs-minimal`
build-libs | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs/1506192656823226368) | true | `/test build-libs`
build-libs-bundled-deps | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-bundled-deps/1506192656923889664) | true | `/test build-libs-bundled-deps`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-22 09:54 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-minimal | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1506192657020358656) | true | `/test build-libs-minimal`
build-libs | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs/1506192656823226368) | true | `/test build-libs`
build-libs-bundled-deps | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-bundled-deps/1506192656923889664) | true | `/test build-libs-bundled-deps`
build-libs-with-chisels | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-with-chisels/1506192656957444096) | true | `/test build-libs-with-chisels`
build-libs-arm | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-arm/1506207422409084928) | true | `/test build-libs-arm`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-22 09:55 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-minimal | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1506192657020358656) | true | `/test build-libs-minimal`
build-libs-bundled-deps | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-bundled-deps/1506192656923889664) | true | `/test build-libs-bundled-deps`
build-libs-with-chisels | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-with-chisels/1506192656957444096) | true | `/test build-libs-with-chisels`
build-libs-arm | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-arm/1506207422409084928) | true | `/test build-libs-arm`
build-libs | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs/1506207422354558976) | true | `/test build-libs`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-22 09:55 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-bundled-deps | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-bundled-deps/1506192656923889664) | true | `/test build-libs-bundled-deps`
build-libs-with-chisels | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-with-chisels/1506192656957444096) | true | `/test build-libs-with-chisels`
build-libs-arm | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-arm/1506207422409084928) | true | `/test build-libs-arm`
build-libs | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs/1506207422354558976) | true | `/test build-libs`
build-libs-minimal | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1506207422581051392) | true | `/test build-libs-minimal`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-22 09:59 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-with-chisels | 363264cd88aceed03127b330c86f7b4d9fe437fc | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-with-chisels/1506192656957444096) | true | `/test build-libs-with-chisels`
build-libs-arm | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-arm/1506207422409084928) | true | `/test build-libs-arm`
build-libs | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs/1506207422354558976) | true | `/test build-libs`
build-libs-minimal | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1506207422581051392) | true | `/test build-libs-minimal`
build-libs-bundled-deps | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-bundled-deps/1506207422467805184) | true | `/test build-libs-bundled-deps`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-22 09:59 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-arm | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-arm/1506207422409084928) | true | `/test build-libs-arm`
build-libs | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs/1506207422354558976) | true | `/test build-libs`
build-libs-minimal | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1506207422581051392) | true | `/test build-libs-minimal`
build-libs-bundled-deps | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-bundled-deps/1506207422467805184) | true | `/test build-libs-bundled-deps`
build-libs-with-chisels | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-with-chisels/1506207422513942528) | true | `/test build-libs-with-chisels`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-22 10:05 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs/1506207422354558976) | true | `/test build-libs`
build-libs-minimal | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-minimal/1506207422581051392) | true | `/test build-libs-minimal`
build-libs-bundled-deps | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-bundled-deps/1506207422467805184) | true | `/test build-libs-bundled-deps`
build-libs-with-chisels | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-with-chisels/1506207422513942528) | true | `/test build-libs-with-chisels`
build-libs-arm | 1c59f390f8d668b3841a15182398980f3ee517eb | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-arm/1506209003720413184) | true | `/test build-libs-arm`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-22 10:05 UTC, poiana commented
@FedeDP: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build-libs-bundled-deps | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-bundled-deps/1506207422467805184) | true | `/test build-libs-bundled-deps`
build-libs-with-chisels | 65645796c8f126b56e2abaa272262eaa728b8fe4 | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-with-chisels/1506207422513942528) | true | `/test build-libs-with-chisels`
build-libs-arm | 1c59f390f8d668b3841a15182398980f3ee517eb | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs-arm/1506209003720413184) | true | `/test build-libs-arm`
build-libs | 1c59f390f8d668b3841a15182398980f3ee517eb | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_libs/86/build-libs/1506209003615555584) | true | `/test build-libs`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=libs&pr=86). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/libs/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-22 11:24 UTC, FedeDP commented
/test build-libs-bundled-deps

2022-03-22 11:57 UTC, FedeDP commented
/test build-libs-with-chisels

2022-04-21 07:46 UTC, FedeDP commented
I think i will split this PR in:
* a PR that adds the flexible array member to struct ppm_evt_hdr to manage events payload + enforces c99 + merges g_syscall_code_routing_table into g_syscall_table
* a PR that uses an m4 script to automatically create syscall tables

The latter is quite opinionated and might not be merged soon; the former instead should have the consensus to be merged.

2022-04-21 08:01 UTC, leogr commented
> I think i will split this PR in:
> 
> * a PR that adds the flexible array member to struct ppm_evt_hdr to manage events payload + enforces c99 + merges g_syscall_code_routing_table into g_syscall_table
> * a PR that uses an m4 script to automatically create syscall tables
> 
> The latter is quite opinionated and might not be merged soon; the former instead should have the consensus to be merged.

Hey @FedeDP 

I totally agree with splitting this into several PRs. I'm also ok with C99. Moreover, I'd suggest documenting somewhere the C standard we are going to use.

2022-04-22 14:49 UTC, FedeDP commented
I split https://github.com/falcosecurity/libs/pull/298 from this one, with the first point above:
* flexible array member to struct ppm_evt_hdr to manage events payload 
* enforces c99 
* merges g_syscall_code_routing_table into g_syscall_table

This PR (the #86) will instead become only the m4 script one.

2022-04-26 12:46 UTC, FedeDP commented
/hold

2022-04-28 14:34 UTC, FedeDP commented
/test build-libs-bundled-deps

2022-08-28 09:44 UTC, poiana commented
Issues go stale after 90d of inactivity.

Mark the issue as fresh with `/remove-lifecycle stale`.

Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

Provide feedback via https://github.com/falcosecurity/community.

/lifecycle stale

2022-09-27 09:47 UTC, poiana commented
Stale issues rot after 30d of inactivity.

Mark the issue as fresh with `/remove-lifecycle rotten`.

Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

Provide feedback via https://github.com/falcosecurity/community.

/lifecycle rotten

2022-10-27 09:56 UTC, poiana commented
Rotten issues close after 30d of inactivity.

Reopen the issue with `/reopen`.

Mark the issue as fresh with `/remove-lifecycle rotten`.

Provide feedback via https://github.com/falcosecurity/community.
/close

2022-10-27 09:56 UTC, closed without merging

2022-10-27 09:56 UTC, poiana commented
@poiana: Closed this PR.

<details>

In response to [this](https://github.com/falcosecurity/libs/pull/86#issuecomment-1293279907):

>Rotten issues close after 30d of inactivity.
>
>Reopen the issue with `/reopen`.
>
>Mark the issue as fresh with `/remove-lifecycle rotten`.
>
>Provide feedback via https://github.com/falcosecurity/community.
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-10-31 14:14 UTC, FedeDP commented
Most of this PR was split in multiple ones.
We decided to avoid the m4 script, therefore there is not much else we can do.
The only open points are:
* c99
* flexible array member
that are also part of #298 (but i am not sure will ever be implemented).